import codecs
from pathlib import Path
# Emit double-byte Shift-JIS -> Unicode codepoint pairs (JIS X 0208 + extensions),
# sorted by the 16-bit SJIS value. Single-byte ASCII (0x00-0x7F) and halfwidth
# katakana (0xA1-0xDF) are handled algorithmically in the decoder, not tabulated.
pairs = []
for lead in list(range(0x81,0xA0)) + list(range(0xE0,0xFD)):
    for trail in range(0x40,0xFD):
        if trail == 0x7F:
            continue
        b = bytes([lead, trail])
        try:
            s = b.decode('shift_jis')
        except UnicodeDecodeError:
            continue
        if len(s) != 1:
            continue
        cp = ord(s)
        if cp <= 0x7F:
            continue  # would collide with ASCII path; skip degenerate mappings
        sjis = (lead << 8) | trail
        pairs.append((sjis, cp))
pairs.sort()
assert all(cp <= 0xFFFF for _, cp in pairs), "unexpected non-BMP codepoint"
print("count", len(pairs))
lines = ["{0x%04X,0x%04X}" % (sjis, cp) for sjis, cp in pairs]
# chunk into lines of 8 pairs for readability
per = 8
out = ["    " + ",".join(lines[i:i+per]) + "," for i in range(0, len(lines), per)]
dest = Path(__file__).resolve().parent.parent / "src/player/ShiftJisTable.inc"
with open(dest, "w") as f:
    f.write("// Generated by scripts/gen_sjis.py from Python's shift_jis codec. Do not edit by hand.\n")
    f.write("// Sorted {uint16 sjis, uint16 codepoint} pairs for double-byte Shift-JIS sequences.\n")
    f.write("// Regenerate: python3 scripts/gen_sjis.py\n")
    f.write("// clang-format off\n")
    f.write("\n".join(out).rstrip(",")+"\n")
    f.write("// clang-format on\n")
print("wrote", len(pairs), "pairs")
